os: linux
arch: arm64-graviton2
language: c
before_install: 
install: 
script:
- gcc c/main.c -lm -o c/main -Wall
- ls c/ -la
- ldd c/main
after_success:
- echo "build succeed!"
- echo "commit id -> 774a070"
branches:
  only:
  - master
  - dev
addons: ssh_known_hosts:daviddong.github.io
cache: bundler
notifications:
  email: true
env:
  global:
    secure: iQew9eAgyfKHMrO1KdvOww6s8pQBi4MuJbby5pn9cyrkhg7JfyX2NueoTRKrq26Qmdgqkc4yVhHlvHl6ozCs8Iv1D0NuQmK7UoyfSUbDXbfbl4xyfNzc2dXwIY6XJIaUqnnD6EFntMjqzTG1F5L2qiv1KcFAZQo5xwso96Y/yTYF7UQd1QRY0sV9EeWjXJWKycMjk28a9vcopieEzST5R4h2hN2yBCsSmMef4kdsjLFz34emlnk3r0EBRyW+o17IkqMNYFVGW3VBy19k34A7DQzb1nwPd34ZIBSIvEtQ6EivuIc27Bm5QzxYiaC2SNW7neb6MHRSqnmzx0InXTD4cjLxnevRaf7KAhva5sFqDiaR03aGm5PFWbZx+JqeMM4KWOPHWAG962Ud3Hhr/S7xrE4Lj5MSBf7NpC2jP0txXJVtJilvBl+zc6JHKy0rz1Y9C3bUPwrguvT+fKOmkpzHkqoMwrwOXDUtcuUyFSH8UaffBmKREfN8x3rYHBjIEG1zZ/a+kREpQXPmv4/wNSN1a9b7PFLhYv+glYA4mVE8I9K4IBm6YqHkqZcHhtfhXRTfBn1soFJAdB6TI0T8ftoZTtRET6rdEGY0p1bwpzujbLqMxvuCZb62qsPEx69X9s8GKbjC49+0qW4VtNOzpYpCg5GXg9PGtkOhB+mahri5xLQ=
